name: ventmode
dependencies:
  - python=3.8
  - ipython
  - cython
  - numpy
  - pandas
  - pytorch>=1.0
  - torchvision
  - cudatoolkit
  - seaborn
  - scipy>=1.1
  - scikit-learn
  - matplotlib
  - pyqt
  - pip
  - pip:
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - prettytable
    - ventmap
